package com.todolist;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;



public class EditForm  extends HttpServlet{
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		PrintWriter pw=response.getWriter();
		
		String pid=request.getParameter("id");
		int id=Integer.parseInt(pid);
		
		GetSet gt = JdbcOperations.getProductById(id);
		
		pw.print("<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "<meta charset=\"UTF-8\">\r\n"
				+ "<title>Insert title here</title>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "	<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "<meta charset=\"ISO-8859-1\">\r\n"
				+ "<title>ToDoListApp</title>\r\n"
				+ "<link\r\n"
				+ "	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n"
				+ "	rel=\"stylesheet\"\r\n"
				+ "	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n"
				+ "	crossorigin=\"anonymous\">\r\n"
				+ "<script\r\n"
				+ "	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n"
				+ "	integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n"
				+ "	crossorigin=\"anonymous\"></script>\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "<body style=\"background-color: rgb(211, 211, 211);\">\r\n"
				+ "\r\n"
				+ "	<nav class=\"navbar navbar-expand-lg navbar-light bg-dark\">\r\n"
				+ "		<div class=\"container\">\r\n"
				+ "			<a class=\"navbar-brand\" href=\"index.html\"><h3><b style=\"color: white;\">ToDoListApp</h3></b></a>\r\n"
				+ "			<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n"
				+ "				data-target=\"#navbarTogglerDemo02\"\r\n"
				+ "				aria-controls=\"navbarTogglerDemo02\" aria-expanded=\"false\"\r\n"
				+ "				aria-label=\"Toggle navigation\">\r\n"
				+ "				<span class=\"navbar-toggler-icon\"></span>\r\n"
				+ "			</button>\r\n"
				+ "		</div>\r\n"
				+ "					<h5><a class=\"nav-link\" href=\"status\" style=\"color: white; float: right;\">TaskStatus</a></h5>\r\n"
				+ "		\r\n"
				+ "	</nav><br><br>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<div class=\"container\">\r\n"
				+ "<section class=\"vh-100\" style=\"background-color: #eee;\">\r\n"
				+ "  <div class=\"container h-100\">\r\n"
				+ "    <div class=\"row d-flex justify-content-center align-items-center h-100\">\r\n"
				+ "      <div class=\"col-lg-12 col-xl-11\">\r\n"
				+ "        <div class=\"card text-black\" style=\"border-radius: 25px;\">\r\n"
				+ "          <div class=\"card-body p-md-5\">\r\n"
				+ "            <div class=\"row justify-content-center\">\r\n"
				+ "              <div class=\"col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1\">\r\n"
				+ "\r\n"
				+ "                <p class=\"text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4\">To Do List </p>\r\n"
				+ "\r\n"
				+ "                <form class=\"mx-1 mx-md-4\" action=\"UpdateRecord\" method=\"post\">\r\n"
				+ "                <div class=\"d-flex flex-row align-items-center mb-4\">\r\n"
				+ "                    <i class=\"fas fa-user fa-lg me-3 fa-fw\"></i>\r\n"
				+ "                    <div class=\"form-outline flex-fill mb-0\">\r\n"
				+ "                          <label class=\"form-label\" for=\"form3Example1c\">Task Number</label>\r\n"
				+ "                          <input value='"+gt.getId()+"' type=\"text\" class=\"form-control\" name=\"Tid\" />\r\n"
				+ "                    </div>\r\n"
				+ "                  </div>\r\n"
				+ "                  \r\n"
				+ "                  <div class=\"d-flex flex-row align-items-center mb-4\">\r\n"
				+ "                    <i class=\"fas fa-user fa-lg me-3 fa-fw\"></i>\r\n"
				+ "                    <div class=\"form-outline flex-fill mb-0\">\r\n"
				+ "                          <label class=\"form-label\" for=\"form3Example1c\">Task</label>\r\n"
				+ "                          <input value='"+gt.getTask()+"' type=\"text\" class=\"form-control\" name=\"Ttask\" />\r\n"
				+ "                    </div>\r\n"
				+ "                  </div>\r\n"
				+ "\r\n"
				+ "                  <div class=\"d-flex flex-row align-items-center mb-4\">\r\n"
				+ "                    <i class=\"fas fa-envelope fa-lg me-3 fa-fw\"></i>\r\n"
				+ "                    <div class=\"form-outline flex-fill mb-0\">\r\n"
				+ "                       <label class=\"form-label\" for=\"form3Example3c\">Due Date</label>\r\n"
				+ "                      <input value='"+gt.getDuedate()+"' type=\"Date\"  class=\"form-control\" name=\"Tduedate\"/>\r\n"
				+ "                    </div>\r\n"
				+ "                  </div>\r\n"
				+ "                  \r\n"
				+ "                  <div class=\"d-flex flex-row align-items-center mb-4\">\r\n"
				+ "                    <i class=\"fas fa-lock fa-lg me-3 fa-fw\"></i>\r\n"
				+ "                    <div class=\"form-outline flex-fill mb-0\">\r\n"
				+ "                      <label class=\"form-label\" for=\"form3Example4c\">Status</label>  \r\n"
				+ "                         \r\n"
				+ "                      <input value='"+gt.getStatus()+"' type=\"text\"  class=\"form-control\" name=\"Tstatus\" />\r\n"
				+ "                    </div>\r\n"
				+ "                  </div>                 \r\n"
				+ "                  <div class=\"d-flex justify-content-center mx-4 mb-3 mb-lg-4\">\r\n"
				+ "                    <button type=\"submit\" class=\"btn btn-primary btn-lg\">update</button>\r\n"
				+ "                  </div>\r\n"
				+ "\r\n"
				+ "                </form>\r\n"
				+ "\r\n"
				+ "              </div>\r\n"
				+ "              <div class=\"col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2\">\r\n"
				+ "\r\n"
				+ "                <img src=\"https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp\"\r\n"
				+ "                  class=\"img-fluid\" alt=\"Sample image\">\r\n"
				+ "\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "        </div>\r\n"
				+ "      </div>\r\n"
				+ "    </div>\r\n"
				+ "  </div>\r\n"
				+ "</section>\r\n"
				+ "\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "</body>\r\n"
				+ "</html>\r\n"
				+ "\r\n"
				+ "</body>\r\n"
				+ "</html>");

}
}